### ISSUE TITLE
About FID

### ISSUE THREAD

**Issue by h944146914** [SayedNadim/Inpainting_Evaluation_Metrics#1]
Hi,Your work is so good.When to provide FID? Thanks!

**Comment by SayedNadim** [comment]
Hi,
I will provide FID within this month.
Cheers!

**Comment by SayedNadim** [comment]
Hi, sorry for the late reply. I was busy with some work.
Please refer to this new [repo](https://github.com/SayedNadim/Image-Quality-Evaluation-Metrics) for the metrics. I have updated it.
Please let me know if you need any more metrics.
Thanks

**Comment by SayedNadim** [comment]
Can I close this issue?

**Comment by h944146914** [comment]
> Can I close this issue?

Thanks！Your work helps me a lot！of course
